### ISSUE TITLE
Error on connecting to the device

### ISSUE THREAD

**Issue by tpazderka** [koying/jellyfin_ha#12]
I am receiving an error upon connecting.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 501, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/jellyfin/sensor.py", line 93, in extra_state_attributes
    if self.jelly_cm.data:
  File "/config/custom_components/jellyfin/__init__.py", line 867, in data
    "number": f'S{item["ParentIndexNumber"]}E{item["IndexNumber"]}',
KeyError: 'ParentIndexNumber'
```
From the point of jellyfins, it looks like everything is working just fine as I can see several API calls from the HA user receiving data.

If there is anything I can do to help troubleshooting the issue, please let me know.

**Comment by Hukuma1** [comment]
```
Logger: homeassistant.components.sensor
Source: custom_components/jellyfin/__init__.py:867
Integration: Sensor (documentation, issues)
First occurred: 11:21:56 AM (2 occurrences)
Last logged: 11:21:56 AM

Error adding entities for domain sensor with platform jellyfin
Error while setting up jellyfin platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/jellyfin/sensor.py", line 93, in extra_state_attributes
    if self.jelly_cm.data:
  File "/config/custom_components/jellyfin/__init__.py", line 867, in data
    "number": f'S{item["ParentIndexNumber"]}E{item["IndexNumber"]}',
KeyError: 'IndexNumber'
```

Getting the exact same issue. Jellyfin works with no issues/errors. I have no limits on my user logins (0). Anyway to debug this? Would love to use this with Custom Upcoming Card.
