### ISSUE TITLE
Unexpected Keyword error when using Browse service

### ISSUE THREAD

**Issue by boardwarp** [koying/jellyfin_ha#21]
While the integration seems to be working fine for me otherwise, when attempting to use the Browse service, an error like this appears in the HA logs:

```
2021-12-03 14:00:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140194619643744] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 523, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/jellyfin/__init__.py", line 183, in async_service_handler
    await getattr(media_player, method['method'])(**params)
TypeError: async_browse_item() got an unexpected keyword argument 'id'
```

In the past I had this working to browse to either a whole library or individual media item, but now trying either will result in the above. The IDs are copied from the `id` parameter in the Jellyfin webUI URLs, and work fine to play media with.

**Comment by koying** [comment]
Ficed by c386221f3ada92d360b997d888c1154fe90297a in 1.0.8
