### ISSUE TITLE
No more entities

### ISSUE THREAD

**Issue by Skuair** [koying/jellyfin_ha#37]
Hi,

I don't know from when, maybe jellyfin server update or HA recent update but my media player entities where in status restored. I deleted the integration and reinstalled it but now, there is no more media player entities.

Here are the HA logs:
Logger: JELLYFIN.jellyfin_apiclient_python.ws_client
Source: /usr/local/lib/python3.10/site-packages/jellyfin_apiclient_python/ws_client.py:85
First occurred: 22:42:44 (1 occurrences)
Last logged: 22:42:44
'socket' object has no attribute 'pending'

And another one:
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:336
First occurred: 22:42:44 (1 occurrences)
Last logged: 22:42:44

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websocket/_app.py", line 354, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/usr/local/lib/python3.10/site-packages/websocket/_app.py", line 70, in read
    r = self.select()
  File "/usr/local/lib/python3.10/site-packages/websocket/_app.py", line 78, in select
    if sock.pending():
AttributeError: 'socket' object has no attribute 'pending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/jellyfin_apiclient_python/ws_client.py", line 72, in run
    self.wsc.run_forever(
  File "/usr/local/lib/python3.10/site-packages/websocket/_app.py", line 420, in run_forever
    setSock()
  File "/usr/local/lib/python3.10/site-packages/websocket/_app.py", line 356, in setSock
    handleDisconnect(e)
  File "/usr/local/lib/python3.10/site-packages/websocket/_app.py", line 407, in handleDisconnect
    dispatcher.timeout(reconnect, setSock)
AttributeError: 'SSLDispatcher' object has no attribute 'timeout'

Thanks.

**Comment by mLgz0rn** [comment]
Same here.

And when it finally add new entities they are just unavailable, no status update

**Comment by Skuair** [comment]
> Same here.
> 
> And when it finally add new entities they are just unavailable, no status update

Same yes, after 1 day maybe, the entity showed up but is unavailable.

**Comment by andreasc1** [comment]
Yes @koying it seems that it conflicts/clashes with the official integration, can you somehow diferentiate the two so we can configure this integration which seems that it provides additional functionality?
