### ISSUE TITLE
local variable 'url' referenced before assignment

### ISSUE THREAD

**Issue by XiaoKe89** [koying/jellyfin_ha#8]
Hi, I keep getting this error whenever I try to play any videos using this integration. Music files work just fine it just does this with the videos. Is there something I'm missing? Or is this a bug, and if so is there any kind of workaround?

Here is the full log out gives with the error:

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/jellyfin/__init__.py:1264
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:20:21 PM (1 occurrences)
Last logged: 5:20:21 PM

[281473142058432] local variable 'url' referenced before assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 453, in async_play_media
    sourced_media = await media_source.async_resolve_media(self.hass, media_id)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 85, in async_resolve_media
    return await _get_media_item(hass, media_content_id).async_resolve()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 83, in async_resolve
    return await self.async_media_source().async_resolve_media(self)
  File "/config/custom_components/jellyfin/media_source.py", line 116, in async_resolve_media
    t = await self.jelly_cm.get_stream_url(media_content_id, media_content_type)
  File "/config/custom_components/jellyfin/__init__.py", line 1264, in get_stream_url
    _LOGGER.debug("stream info: %s - url: %s", info, url)
UnboundLocalError: local variable 'url' referenced before assignment
`

**Comment by koying** [comment]
Hi. Please set the component in "debug" and provide the logs.
Thanks.

```yaml
logger:
  default: info
  logs:
    custom_components.jellyfin: debug
    JELLYFIN.jellyfin_apiclient_python: debug
    JELLYFIN.jellyfin_apiclient_python.ws_client: debug

```

**Comment by XiaoKe89** [comment]
Is this what you're looking for?
https://pastebin.com/VEXprrUJ

**Comment by koying** [comment]
Hi. Yes, but I'd need you to reproduce the issue, *then* sending me those logs.
Thanks

**Comment by XiaoKe89** [comment]
Ah gotcha, try this one: https://pastebin.com/C9WVX3dF

**Comment by koying** [comment]
Thanks.
The problem here is that the file is basically not playable: `'SupportsTranscoding': False, 'SupportsDirectStream': False, 'SupportsDirectPlay': False`
I'll fix that in the integration code.
